exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-commonmark
  - jekyll-include-cache
paginate: 100
paginate_path: 'blog/page:num'

collections:
  posts:
    title: Posts
    output: true
    description: My thoughts and ideas
    feature_text: |
      Welcome to the blog
    feature_image: 'https://picsum.photos/2560/600?image=866'

defaults:
  - scope:
      path: ''
    values:
      image: /assets/default-social-image.png
  - scope:
      path: ''
      type: posts
    values:
      layout: post
  - scope:
      path: ''
      type: pages
    values:
      layout: page

fonts:
  preconnect_urls:
    - 'https://fonts.gstatic.com'
  font_urls:
    - https://fonts.googleapis.com/css2?family=Palatino:wght@400;700&display=swap

title: Cogito
description: 'Noble and Greenough School'
logo: /shield.png

navigation_header:
  - title: Cogito XIV
    url: /
  - title: About
    url: /about
  - title: Publications
    url: /publications

latest: Cogito XIV

staff:
  - position: Editors-in-Chief
    names:
      - Katie Cheung
      - Angie Feng
  - position: Executive Managers
    names:
      - Will Grimes
      - Jackie Zhang
  - position: Layout Manager
    names:
      - Helen Cui
  - position: Managing Editors
    names:
      - Mara DuBois
      - Corban Shih
      - Chris Tillen
  - position: Copy Editors
    names:
      - Alan Cai
      - Morgan Gibson
      - Arnav Harve
      - Simon Juknelis
      - Joanne Lee
      - Colin Levine
      - Clare Struzziery
      - Ashley Wang
      - Eric Zhou
  - position: Layout Editors
    names:
      - Emily Bao
      - Morgan Gibson
      - Will Hesp
      - Arthi Vithiananthan
      - Ashley Wang
      - Alex Yi
      - Eric Zhou
  - position: Webmaster
    names:
      - Simon Juknelis
navigation_footer:
  - title: Back to top
    url: '#top'
sharing_links:
  Twitter: '#0d94e7'
  Facebook: '#3B5998'
  Email: true
